name = "create-serversided"
author = "Poellebob"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3fa6d84c938a699b07cffb529527864c18e7b771b0817952bb940309c73fc23"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
