name = "create-serversided"
author = "Poellebob"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80f6cdb38aab8db131df0e4994a792f8d39969c77b28b2ab9a61defdc9272215"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
